services:

  video_service:
    build: 
      context: .
      dockerfile: ./deploy/Dockerfile
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - video-service-db

  video-service-db:
    image: postgres:latest
    restart: always
    env_file:
      -  .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/
    ports:
      - ${DB_PORT_EXTERNAL}:5432

volumes:
  postgres-db:

networks:
  default:
      name: stargazer_network
      external: true