package enums

const (
	Terminalreset     = "\033[0m"
	Terminalbold      = "\033[1m"
	Terminalunderline = "\033[4m"
	Terminalstrike    = "\033[9m"
	Terminalitalic    = "\033[3m"

	TerminalcRed    = "\033[31m"
	TerminalcGreen  = "\033[32m"
	TerminalcYellow = "\033[33m"
	TerminalcBlue   = "\033[34m"
	TerminalcPurple = "\033[35m"
	TerminalcCyan   = "\033[36m"
	TerminalcWhite  = "\033[37m"
)

const (
	InvalidSchmea_NullEntry = "Failed in Parsing Input! Invalid Schema/Null Entry"
	ErrorCreatingNew        = "Failed in Creating New Entry"
	ErrorDecodingJson       = "Error Decoding JSON / Unable to Unmarshal Request Body"
	ErrorEncodingJson       = "Error Marshalling Response"
	HeraldRequestFailed     = "Error in request made to Herald"
	ErrorReadingFile        = "Error in Reading RBAC Config Files!"
	ErrorWritingFile        = "Error in Writing RBAC Config Files!"

	IOReadErr                  = "IO Read Failed"
	OAuth2CodeFailed           = "OAuth2 Code Request Failed"
	OAuth2CodeNotFound         = "oauth2 code not found"
	OAuth2Failed               = "OAuth2 failed! unable too retrieve user data"
	DBEntryFailed              = "Error Adding New Data to DB"
	DBRetrieveFailed           = "Error Retrieving Data from DB"
	DBUpdateFailed             = "Error Updating Data in DB"
	ExternalGetFailed          = "Failed in Doing External Get Request"
	ErrorSigningJWT            = "Error Signing JWT"
	ErrorVerifyingJWT          = "Failed to Verify JWT | Token Recieved is either malformed/expired"
	PassHashFailed             = "Error Hashing Password"
	Issuer                     = "PaperKite-Cavalry"
	Access_token               = "AccessToken"
	Refresh_token              = "RefreshToken"
	Update_token               = "UpdateToken"
	UnAuthorizedAccess         = "UnAuthorized Access Encountered"
	InternalCommsError         = "Internal Communications Failed / Service Unavailable"
	InternalError              = "Internal Crash!"
	OAuthExchangeFailed        = "Error in exchanging oauth tokens"
	DBAddRetrieveFailed        = "Error in Adding Data to DB hence no response"
	CSVDecodeFailed            = "CSV Decode Failed"
	CookieNotFound             = "Active Session Not Found, Login First!"
	UnhandledInternalError     = "It Looks like Something Unusal has happened. The issue have been logged and our team will soon look into the issue."
	EnvLoadFailed              = "Failed to load env file!"
	HeraldConnFailed           = "Error Connecting to Herald Server"
	FileUploadFailed           = "Error processing file upload"
	FileDecodeFailed           = "Empty File received"
	ValidationFailed           = "Error Validating request body"
	JwtParseFailed             = "JWT Parse failed"
	TypeConvertionFailed       = "type convertion failed"
	RedisReadFailed            = "Failed to read data from redis"
	SessionExpired             = "Session Expired Login Again"
	RefreshTokenNotFound       = "RefreshTokenNotFound"
	CachReadErr                = "error reading data from redis"
	AWS_S3_REGION              = "us-east-2"
	QueueDeclareFailed         = "failed to declare message queue "
	MQConnFailed               = "Error connnecting to message queue"
	AWS_S3_BUCKET              = "paperkite-s3"
	LoginAlert                 = "LoginAlert"
	AvatarKey                  = "Avatar"
	TaskUploadAvatar           = "uploadAvatar"
	Minion                     = "minions"
	Sessions                   = "sessions"
	PosgresAuthFailed          = "Failed to Connect with Postgres"
	PostgresPingFailed         = "Failed to Ping Postgres DB"
	MigrationsFailed           = "DB Migrations Failed"
	PostgresBulKCreationFailed = "Failed to Bulk Insert data into postgres"
	PgAddFailed                = "Failed to Create New Entry in Postgres DB"
	PgUpdateFailed             = "Failed to Update New Entry in Postgres"
	PgDeleteFailed             = "Failed to delete Entry"
	PgFetchFailed              = "Failed to Get Entry"
	TwilioCookieKey            = "twilio-room"
	MediaConvertNotStarted     = "Not-Started"
	MediaConvertStarted        = "Started"
	MediaConvertOnGoing        = "OnGoing"
	MediaConvertFinished       = "Finished"
	MediaConvertFailed         = "Failed"
	RoomStatusOnGoing          = "On-Going"
	RoomStatusClosed           = "Closed"
	Ok                         = "ok"
)
